[package]
name = "sqdj"
version = "0.2.1"
edition = "2021"
authors = ["Dhruv Thakur"]
repository = "https://github.com/dhth/squidge"
description = "sqdj shortens delimited data"
homepage = "https://github.com/dhth/squidge"
license = "MIT"
keywords = [
    "cli",
    "delimited",
    "shortener",
]
categories = [
    "command-line-utilities",
    "text-processing"
]

[dependencies]
squidge = { version = "0.2.1", path = "../squidge" }
clap = { version = "4.5.18", features = ["derive"] }
regex = "1.10.6"
