[package]
name = "sqdj"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description = "sqdj shortens delimited data"
keywords = [
    "cli",
    "delimited",
    "shortener",
]
categories = [
    "command-line-utilities",
    "text-processing"
]

[dependencies]
squidge = { version = "0.2.1", path = "../squidge" }
clap = { version = "4.5.20", features = ["derive"] }
regex.workspace = true
