[package]
name = "squidge"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/dhth/squidge"
description = "squidge shortens delimited data"
homepage = "https://github.com/dhth/squidge"
license = "MIT"

[dependencies]
regex = "1.10.6"
